spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbj?useSSL=false
    username: root
    password: diao
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true